GET http://localhost:3002/api HTTP/1.1
###

GET https://localhost:3002/api HTTP/1.1
### 

GET https://localhost:3002/api/bulletinBoards HTTP/1.1
###

DELETE https://localhost:3002/api/bulletinBoards/6527f1f58b9f3cdfea20eeeb HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvdmVybm1lbnRBZ2VudCIsInVzZXJpZCI6IjY1MjdmMTM5OGI5ZjNjZGZlYTIwZWVlOCIsImlhdCI6MTY5NzExNjU2NywiZXhwIjoxNjk3MTIwMTY3fQ.YHUzqgtNDpThinNF1lvsv0r4reXMvW7LJvpPiSi3X_g

###

POST https://localhost:3002/api/bulletinBoards HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvdmVybm1lbnRBZ2VudCIsInVzZXJpZCI6IjY1MjdmMTM5OGI5ZjNjZGZlYTIwZWVlOCIsImlhdCI6MTY5OTI5Mjc0MSwiZXhwIjoxNjk5Mjk2MzQxfQ.6oqz-A_1k7SeVk8kcTgLin4wRMobuLgaAf9Slv_l1H0

{
  "id" : "post001", 
    "caption" : "Help2", 
}
###

POST https://localhost:3002/api/users/signup HTTP/1.1
content-type: application/json

{
    "username": "governmentAgent",
    "password": "IamNotASpy#123"
}
###

POST https://localhost:3002/api/users/login HTTP/1.1
Content-Type: application/json

{
 "username": "governmentAgent",
 "password": "IamNotASpy#123"
}
###